version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:admin@mongodb:27017/url_shortener_db?authSource=admin
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
  mongodb:
    image: mongo:jammy
    container_name: url_shortener_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - url_shortener_mongodb_data:/data/db

volumes:
  url_shortener_mongodb_data:
    driver: local
